vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        image_profil:
            uri_prefix: /images/image_profil
            upload_destination: '%kernel.project_dir%/public/images//image_profil'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
